import type { EdgeDevice, EdgeDeviceEvent } from "./types.js";

export interface EdgeDevicesRepository {
  createDevice(device: EdgeDevice): Promise<void>;
  getDeviceById(deviceId: string): Promise<EdgeDevice | null>;
  listDevicesForOrg(organizationId: string): Promise<EdgeDevice[]>;
  updateDevice(device: EdgeDevice): Promise<void>;
  deactivateDevice(deviceId: string): Promise<void>;

  /** Idempotency check for event ingestion -- event_id is globally unique, generated by the device. */
  getEventByEventId(eventId: string): Promise<EdgeDeviceEvent | null>;
  appendEvent(event: EdgeDeviceEvent): Promise<void>;
  listEventsForDevice(
    deviceId: string,
    opts?: { eventType?: EdgeDeviceEvent["eventType"]; limit?: number },
  ): Promise<EdgeDeviceEvent[]>;

  /**
   * Bulk status transition for the health sweep (offline/degraded
   * detection). Returns the number of rows changed. A real (Postgres)
   * implementation should do this as bulk UPDATEs, not a fetch-all +
   * loop -- mirrors AgentSyncService.sweep_offline_agents in Aegis,
   * which did the same for the same reason (a large fleet shouldn't
   * mean loading every row into memory every sweep interval).
   */
  sweepStaleDevices(
    degradedThreshold: Date,
    offlineThreshold: Date,
  ): Promise<{ markedDegraded: number; markedOffline: number }>;

  /** Flags active (non-offline) devices in an org as needing a policy resync. Returns the count flagged. */
  flagPendingSyncForOrg(organizationId: string, reason: string): Promise<number>;
}
