/**
 * Edge-Devices: fleet management for Aegis enforcement agents -- customer-
 * deployed components (hybrid/on-prem) that enforce AI governance policy
 * close to the traffic and report back here. Consolidated in from Aegis's
 * backend (`enforcement_agents` / `agent_events` tables,
 * `AgentSyncService`) per CUTOVER.md: Command Center owns fleet identity,
 * heartbeat, and event transport; Aegis keeps policy compilation (turning
 * an org's Policy/AutomationRule records into the snapshot an edge device
 * enforces), since that's product/GRC domain logic, not fleet plumbing.
 *
 * Deliberately a distinct module from Customer-Connections/Desktop-Apps:
 * an edge device is a policy-enforcement component a customer deploys in
 * their own VPC or on-prem, not the Aegis desktop GUI. Different
 * protocol, different lifecycle, different auth headers on the wire --
 * conflating them would be the same mistake Aegis and Command Center
 * independently avoided by having two different tables in the first
 * place, just now recognized as belonging in the same system.
 */

export type EdgeDeviceDeploymentType = "saas" | "hybrid" | "on_prem" | "vpc";
export type EdgeDeviceStatus = "provisioning" | "active" | "degraded" | "offline" | "inactive";
/**
 * Runtime values for EdgeDeviceStatus -- the type alias above has no
 * runtime representation, and Platform-Services/Subscriptions/src/vocabulary.test.ts
 * needs one to check against Aegis's mirrored AgentStatus values (the
 * two are deliberately kept identical; this is what catches it if they drift).
 */
export const EDGE_DEVICE_STATUS_VALUES: readonly EdgeDeviceStatus[] = [
  "provisioning",
  "active",
  "degraded",
  "offline",
  "inactive",
];

export type EdgeDeviceEventType =
  | "heartbeat"
  | "agent_started"
  | "agent_stopped"
  | "config_reload"
  | "prompt_allowed"
  | "prompt_blocked"
  | "policy_violation"
  | "policy_sync_ack"
  | "error";

export type EdgeDeviceEventSeverity = "info" | "warning" | "error" | "critical";

export interface EdgeDevice {
  id: string;
  organizationId: string;
  name: string;
  description: string | null;
  deploymentType: EdgeDeviceDeploymentType;
  environment: string | null;
  version: string | null;
  apiKeyHash: string;
  apiKeyPrefix: string;
  status: EdgeDeviceStatus;
  lastHeartbeat: Date | null;
  /** SHA-256-style fingerprint of the last policy snapshot this device is known to have. Compiled and set by Aegis, not Command Center -- Command Center just stores and compares it. */
  policySnapshotVersion: string | null;
  lastPolicySync: Date | null;
  /** Set by signalPendingSync when Aegis reports a policy change; cleared by the device's own policy_sync_ack event or an operator-triggered resync. */
  pendingSync: boolean;
  pendingSyncReason: string | null;
  ipAllowlist: string[] | null;
  isActive: boolean;
  metadata: Record<string, unknown> | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface EdgeDeviceEvent {
  id: string;
  edgeDeviceId: string;
  organizationId: string;
  /** Idempotency key generated by the device itself -- see ingestEvents in events.ts. */
  eventId: string;
  eventType: EdgeDeviceEventType;
  severity: EdgeDeviceEventSeverity;
  payload: Record<string, unknown> | null;
  occurredAt: Date | null;
  receivedAt: Date;
}

export interface RegisterEdgeDeviceInput {
  organizationId: string;
  name: string;
  description?: string | null;
  deploymentType: EdgeDeviceDeploymentType;
  environment?: string | null;
  ipAllowlist?: string[] | null;
  metadata?: Record<string, unknown> | null;
}

export interface EdgeDeviceEventInput {
  eventId: string;
  eventType: EdgeDeviceEventType;
  severity?: EdgeDeviceEventSeverity;
  payload?: Record<string, unknown> | null;
  /** ISO-8601 string, matching what a device actually sends over the wire -- parsed to a Date at the domain boundary, same pattern as Desktop-Apps's telemetry. */
  occurredAt?: string | null;
}

export interface EventIngestSummary {
  accepted: number;
  duplicate: number;
  invalid: number;
}
